### ISSUE TITLE
ModuleNotFoundError when importing EvLFU

### ISSUE THREAD

**Issue by nippleshot** [ucare-uchicago/ev-store-dlrm#1]
Hello, @daniarherikurniawan 

When I tried to [insert the data to DB](https://github.com/ucare-uchicago/ev-store-dlrm/blob/main/experiments.md#1-insert-the-data-to-db-dont-limit-the-ram), I got ModuleNotFoundError when importing EvLFU :
```c
root@03480a7d191b:/mnt/extra/ev-store-dlrm# ./bench/dlrm_s_criteo_kaggle_C1.sh "--load-model=model.pth --input-data=./input/$input_data --ev-path=stored_model/$input_data/epoch-00/ev-table --inference-only=True --mlperf-logging --percent-data-for-inference=0.0001  --cache-size=1500 --ev-precs=32 --use-gpu=True --use-evstore=True --use-emb-cache=True --overwrite-db=True --emb-stor=rocksdb"
run pytorch C1 ...
Traceback (most recent call last):
  File "/mnt/extra/ev-store-dlrm/dlrm_s_pytorch_C1.py", line 75, in <module>
    import EvLFU_C1
  File "/mnt/extra/ev-store-dlrm/cache_algo/EvLFU_C1.py", line 4, in <module>
    import storage_manager
  File "/mnt/extra/ev-store-dlrm/emb_storage/storage_manager.py", line 23, in <module>
    import EvLFU
ModuleNotFoundError: No module named 'EvLFU'
finished!
```

At storage_manager.py `sys.path.append`, I write down full path for [EvLFU.cpython-36m-x86_64-linux-gnu.so ](cache_algo/EvLFU_C1_Cython/EvLFU.cpython-36m-x86_64-linux-gnu.so)like this :
`sys.path.append('/mnt/extra/ev-store-dlrm/cache_algo/EvLFU_C1_Cython')`
but I'm still having same ModuleNotFoundError

btw these are the result for `print(sys.path)` : 
```c
['/mnt/extra/ev-store-dlrm', '/opt/conda/lib/python310.zip', '/opt/conda/lib/python3.10', '/opt/conda/lib/python3.10/lib-dynload', '/opt/conda/lib/python3.10/site-packages', '/opt/conda/lib/python3.10/site-packages/PyYAML-6.0-py3.10-linux-x86_64.egg', '/mnt/extra/mlperf-logging', '/opt/conda/lib/python3.10/site-packages/python_rocksdb-1.0-py3.10-linux-x86_64.egg', 'emb_storage', 'cache_algo', 'cache_algo/EvLFU_C1_Cython', 'emb_storage', '../../', '../../', '../../', '/mnt/extra/ev-store-dlrm/cache_algo/EvLFU_C1_Cython']
```
Is there any other way to solve it?

**Comment by shirinebadi** [comment]
Hi @nippleshot 
I got the same error. Could you solve it?
